### ISSUE TITLE
StrFormat error

### ISSUE THREAD

**Issue by wxli0** [Xtra-Computing/FedTree#38]
I encountered the following error multiple times (for all occurrences of StrFormat) in the "make" stage for FedTree:
```
/projects/FedTree/build/_deps/grpc-src/src/core/lib/surface/call.cc:  in function ‘void handle_error_parsing_compression_algorithm(grpc_call*)’:
/projects/FedTree/build/_deps/grpc-src/src/core/lib/surface/call.cc:1398:51: ERROR：no matching function for call to ‘StrFormat(const char [71], grpc_stream_compression_algorithm&, grpc_message_compression_algorithm&)’
     call->incoming_message_compression_algorithm);
```

I searched this error, and followed the suggestions to upgrade gcc to 7.3.1 on CentOS 7. However, the error still exists. Could you please suggest how to fix it? Many thanks!

**Comment by QinbinLi** [comment]
Hi @wxli0 ,

I'm sorry that I don't know how to fix it since the error comes from compiling grpc. I think there exists an incompatibility between grpc and your compiler (e.g., see [here](https://github.com/grpc/grpc/issues/24940)). If upgrading gcc cannot solve the problem, you may try to change the version of grpc in line72 of [CMakeLists.txt](https://github.com/Xtra-Computing/FedTree/blob/main/CMakeLists.txt). Thanks.
